---
plugin: jira_search
table: jira_search
variables:
  username: ${JIRA_USERNAME}
  password: ${JIRA_PASSWORD}
  endpoint: ${JIRA_ENDPOINT}
  jql: project = "ABC"
---
plugin: nullify_sca_events
table: nullify_sca_events
variables:
  endpoint: ${NULLIFY_ENDPOINT}
  token: ${NULLIFY_TOKEN}
  githubOrgId:  ${NULLIFY_GITHUB_ORG_ID}
  #fromTime: "2006-01-02T15:04:05Z"
---
plugin: write_json
variables:
  output: data/$TABLE/$YYYY/$MM/$DD/$UUID.json
---
plugin: write_s3
variables:
  bucket: my-fancy-bucket-name
  key: data/$TABLE/$YYYY/$MM/$DD/$UUID.json
